In [3]:
import numpy as np

In [5]:
## Arrays
def arrays(arr):
    arr.reverse()
    nparr=np.array(arr,"float")
    return nparr

li=list(map(int,input().split()))
print(arrays(li))

 1 2 3 4 -8 -10


[-10.  -8.   4.   3.   2.   1.]


In [7]:
# Shape and Reshape

listint=list(map(int,input().split()))
arr=np.array([listint])
print(np.reshape(arr,(3,3)))

 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Transpose and Flatten
a,b=input().split()
N=int(a)
M=int(b)

arr=[]
for i in range(N):
    li=input().split()
    subarr=[]
    for j in li:
        subarr.append(int(j))
    arr.append(subarr)
    
my_arr=np.array(arr)

print(np.transpose(my_arr))

print(my_arr.flatten())

 2 2
 1 2
 3 4


[[1 3]
 [2 4]]
[1 2 3 4]


In [11]:
# Concatenate
a,b,c=input().split()

N,M,P=int(a),int(b),int(c)
A1=[]
A2=[]
for i in range(N):
    li=[ int(n) for n in input().split() ]
    A1.append(li)
    
for i in range(M):
    li=[ int(n) for n in input().split() ]
    A2.append(li)

print(np.concatenate( (np.array(A1),np.array(A2)),axis=0 ))


 4 3 2
 1 2
 1 2
 1 2
 1 2
 3 4
 3 4
 3 4


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [13]:
# Zeros and Ones
li=[ int(n) for n in input().split() ]

print( np.zeros( tuple(li),dtype=int )  )
print( np.ones(tuple(li),dtype= int )  )


 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [14]:
# Eye and Identity

np.set_printoptions(legacy='1.13')

N,M=( int(n) for n in input().split())

print(np.eye(N,M,k=0))




 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [15]:
# Array Mathematics
N,M=(int(n) for n in input().split())

A=[]
for i in range(N):
    subarray=[int(n) for n in  input().split()]
    A.append(subarray)

B=[]
for i in range(N):
    subarray=[int(n) for n in  input().split()]
    B.append(subarray)

A=np.array(A,int)
B=np.array(B,int)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)


 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [16]:
# Floor, Ceil and Rint

np.set_printoptions(legacy='1.13')

arr=[ float(n) for n in input().split() ]

arr=np.array(arr)

print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))




 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [17]:
# Sum and Prod

N,M=[int(n) for n in input().split()]

arr=[]
for i in range(N):
    subarray=[int(n) for n in input().split() ]
    arr.append(subarray)

arr=np.array(arr)
li=np.sum(arr,axis=0)

print(np.prod(li))


 2 2
 1 2
 3 4


24


In [18]:
# Min and Max
N,M=[int(n) for n in input().split()]

arr=[]
for n in range(N):
    subarray=[ int(n) for n in input().split() ]
    arr.append(subarray)

arr=np.array(arr)
li=np.min(arr,axis=1)
print(np.max(li))


 4 2
 2 5
 3 7
 1 3
 4 0


3


In [19]:
# Mean, Var, and Std

N,M=[ int(n) for n in input().split()]
arr=[]
for i in range(N):
    subarray=[int(n) for n in input().split()]
    arr.append(subarray)

arr=np.array(arr)
print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(round(np.std(arr),11 ) )

 2 2
 1 2
 3 4


[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [21]:
# Dot and Cross

N = int(input())
A=[]
for i in range(N):
    temp=list(map(int,input().split()))
    A.append(temp)
B=[]
for i in range(N):
    temp=list(map(int,input().split()))
    B.append(temp)
print(np.dot(np.array(A),np.array(B)))

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


In [22]:
# Inner and Outer
A=np.array(list(map(int,input().split())))
B=np.array(list(map(int,input().split())))
print(np.inner(A,B))
print(np.outer(A,B))


 0 1
 2 3


3
[[0 0]
 [2 3]]


In [23]:
# Polynomials

polyCoeff=list(map(float,input().split()))
x=int(input())
print(np.polyval(np.array(polyCoeff),x))

 1.1 2 3
 0


3.0


In [24]:
# Linear Algebra
N=int(input())
A=[list(map(float,input().split())) for _ in range(N) ]
print(round(np.linalg.det(np.array(A)),2))


 2
 1.1 1.1
 1.1 1.1


0.0
